#!/usr/bin/env ruby
require_relative '../lib/mongo_cluster'
require_relative '../lib/control_group'
require_relative '../lib/munin_node'
require_relative '../lib/transparent-hugepages'

TransparentHugepages.init
# ControlGroup.init
MuninNode.init
MongoCluster.init