#!/usr/bin/env ruby
require 'daemons'
require 'rufus-scheduler'
require 'mongo'
require_relative '../lib/mongo_cluster/replica_set'

Daemons.run_proc('users_creator', monitor: true, log_output: true, log_dir: '/tmp') do
  scheduler = Rufus::Scheduler.new
  replica_members =
      MongoCluster::ReplicaSet
      .conf
      .fetch(:members)
      .map {|member| member.fetch(:host)}
  client = Mongo::Client.new(replica_members, database: 'vatbox')
  users = client['users']
  users.drop
  id = 0

  scheduler.interval '1s' do
    users.insert_one(id: id, timestamp: Time.now.to_formatted_s(:db))
    id += 1
  end

  scheduler.join
end